### PR TITLE
Add a 2D MPL_ALLREDUCE interface

### PR DESCRIPTION
**Pull request by towil1**
This has been extracted from ifs-source PR https://git.ecmwf.int/projects/IFS/repos/ifs-source/pull-requests/1269/overview and need to be in fiat before that PR can be merged.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/fiat?pullRequest=19) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/fiat?pullRequest=19) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/fiat?pullRequest=19) it.</sub>

**Review by wdeconinck — APPROVED** [review]
As far as I can see this is OK.

**Comment by towil1** [comment]
> As far as I can see this is OK.

OK, could we please merge this and create a nre fiat release, as we are getting ready to merge the original ifs-source PR?

**Comment by wdeconinck** [comment]
@towil1  version 1.4.0 is ready, containing this contribution.

**Pull request merged**
