### PR TITLE
Synchronise with CY49R1 - ifs-source/contrib/fiat

### PR DESCRIPTION
**Pull request by wdeconinck**
fiat within ifs-source/contrib unfortunately has diverged from this package over the course of the past 2 years.

This PR brings back these changes.

Once merged, a new fiat release will be created, and ifs-source can then link directly to this package.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/fiat?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/fiat?pullRequest=16) before we can accept your contribution.<br/>**1** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: wdeconinck<br/>:x: pcresswell-ec<br/>:x: awnawab<br/>:x: prgillies<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/fiat?pullRequest=16) it.</sub>

**Review by awnawab — APPROVED** [review]
Looks good to me! Thanks a lot @wdeconinck for doing this sync, it will make my plans for ifs-source/contrib a lot easier to execute 🙏

**Comment by marsdeno** [comment]
Agree with @awnawab, thanks a lot @wdeconinck !

**Review by marsdeno — APPROVED** [review]

**Comment by wdeconinck** [comment]
@awnawab these changes are now in version 1.3.0

**Pull request merged**
